name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.5.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  dio: ^5.2.1+1
  flutter_local_notifications: ^9.0.0
  rxdart: ^0.27.2

  path_provider: ^2.0.11
  permission_handler: ^8.2.5
  package_info_plus: ^1.3.0
  share_plus: ^4.5.3
  chopper: ^4.0.3
  collection: ^1.15.0

dev_dependencies:
  lint: ^1.7.2
